#!/bin/bash
set -e

echo "Watching $1 for pattern $2..."

inotifywait -m -e create -e moved_to --format %w%f --recursive . | (
    while read file; do
        if [[ -n $(find "$file" -path "$2" -prune) ]]; then
            $(dirname $0)/ignore-file $file
        fi
    done
)